// services/province_service.dart
class ProvinceService {
  static const Map<String, String> PROVINCE_MAP = {
    'An Giang': 'AG',
    'Bà Rịa - Vũng Tàu': 'VT',
    'Bạc Liêu': 'BL',
    'Bắc Giang': 'BG',
    'Bắc Kạn': 'BK',
    'Bắc Ninh': 'BN',
    'Bến Tre': 'BT',
    'Bình Dương': 'BD',
    'Bình Định': 'BĐ',
    'Bình Phước': 'BP',
    'Bình Thuận': 'BTH',
    'Cà Mau': 'CM',
    'Cao Bằng': 'CB',
    'Cần Thơ': 'CT',
    'Đà Nẵng': 'DN',
    'Đắk Lắk': 'DL',
    'Đắk Nông': 'DNO',
    'Điện Biên': 'DB',
    'Đồng Nai': 'DNA',
    'Đồng Tháp': 'DT',
    'Gia Lai': 'GL',
    'Hà Giang': 'HG',
    'Hà Nam': 'HNA',
    'Hà Nội': 'HN',
    'Hà Tĩnh': 'HT',
    'Hải Dương': 'HD',
    'Hải Phòng': 'HP',
    'Hậu Giang': 'HAG',
    'Hòa Bình': 'HB',
    'Hưng Yên': 'HY',
    'Khánh Hòa': 'KH',
    'Kiên Giang': 'KG',
    'Kon Tum': 'KT',
    'Lai Châu': 'LC',
    'Lạng Sơn': 'LS',
    'Lào Cai': 'LCA',
    'Lâm Đồng': 'LD',
    'Long An': 'LA',
    'Nam Định': 'ND',
    'Nghệ An': 'NA',
    'Ninh Bình': 'NB',
    'Ninh Thuận': 'NT',
    'Phú Thọ': 'PT',
    'Phú Yên': 'PY',
    'Quảng Bình': 'QB',
    'Quảng Nam': 'QNA',
    'Quảng Ngãi': 'QNG',
    'Quảng Ninh': 'QN',
    'Quảng Trị': 'QT',
    'Sóc Trăng': 'ST',
    'Sơn La': 'SL',
    'Tây Ninh': 'TN',
    'Thái Bình': 'TB',
    'Thái Nguyên': 'TNG',
    'Thanh Hóa': 'TH',
    'Thừa Thiên Huế': 'HUE',
    'Tiền Giang': 'TG',
    'TP. Hồ Chí Minh': 'HCM',
    'Trà Vinh': 'TV',
    'Tuyên Quang': 'TQ',
    'Vĩnh Long': 'VL',
    'Vĩnh Phúc': 'VP',
    'Yên Bái': 'YB',
  };

  static String generateCode(String province) {
    final prefix = PROVINCE_MAP[province] ?? 'VN';
    final random = DateTime.now().millisecondsSinceEpoch % 1000000;
    return '$prefix-${random.toString().padLeft(6, '0')}';
  }
}
