name: hello
description: Emergency SOS Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Map
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Date formatting
  intl: ^0.20.2

  # Image picker for media upload
  image_picker: ^1.0.4
  video_player: ^2.8.6
  chewie: ^1.8.1

  google_sign_in: ^6.2.1

  # HTTP requests
  http: ^1.1.0
  web_socket_channel: ^3.0.3
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/